"""make_runs_scenario_id_nullable

Revision ID: 70297a726c69
Revises: a1b2c3d4e5f6
Create Date: 2026-08-22 07:40:16.178121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70297a726c69'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classifications_run_id'), table_name='classifications')
    op.drop_constraint(op.f('classifications_run_id_fkey'), 'classifications', type_='foreignkey')
    op.create_foreign_key(None, 'classifications', 'runs', ['run_id'], ['id'])
    op.drop_constraint(op.f('valid_severity'), 'classifications', type_='check')
    op.drop_constraint(op.f('valid_verdict'), 'classifications', type_='check')
    op.drop_index(op.f('ix_guardrail_results_run_id'), table_name='guardrail_results')
    op.drop_constraint(op.f('guardrail_results_run_id_fkey'), 'guardrail_results', type_='foreignkey')
    op.create_foreign_key(None, 'guardrail_results', 'runs', ['run_id'], ['id'])
    op.drop_constraint(op.f('valid_confirmation_type'), 'guardrail_results', type_='check')
    op.drop_constraint(op.f('valid_result'), 'guardrail_results', type_='check')
    op.add_column('runs', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('runs', 'scenario_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_runs_agent_version_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_scenario_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_started_at'), table_name='runs')
    op.drop_index(op.f('ix_runs_trace_gin'), table_name='runs', postgresql_using='gin')
    op.drop_index(op.f('ix_scenarios_created_at'), table_name='scenarios')
    op.drop_constraint(op.f('valid_category'), 'scenarios', type_='check')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(op.f('valid_category'), 'scenarios', "category::text = ANY (ARRAY['TOOL_CALL_LOOP'::character varying, 'HALLUCINATED_CONFIDENCE'::character varying, 'DESTRUCTIVE_ACTION'::character varying, 'GOAL_DRIFT'::character varying, 'PROMPT_INJECTION'::character varying, 'WRONG_TOOL'::character varying, 'PREMATURE_COMPLETION'::character varying, 'UNCATEGORIZED'::character varying]::text[])")
    op.create_index(op.f('ix_scenarios_created_at'), 'scenarios', ['created_at'], unique=False)
    op.create_index(op.f('ix_runs_trace_gin'), 'runs', ['trace'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_runs_started_at'), 'runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_runs_scenario_id'), 'runs', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_runs_agent_version_id'), 'runs', ['agent_version_id'], unique=False)
    op.alter_column('runs', 'scenario_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('runs', 'created_at')
    op.create_check_constraint(op.f('valid_result'), 'guardrail_results', "result::text = ANY (ARRAY['HELD'::character varying, 'BYPASSED'::character varying]::text[])")
    op.create_check_constraint(op.f('valid_confirmation_type'), 'guardrail_results', "confirmation_type::text = ANY (ARRAY['PROMPT_BASED'::character varying, 'TOOL_BASED'::character varying, 'NONE'::character varying]::text[])")
    op.drop_constraint(None, 'guardrail_results', type_='foreignkey')
    op.create_foreign_key(op.f('guardrail_results_run_id_fkey'), 'guardrail_results', 'runs', ['run_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_guardrail_results_run_id'), 'guardrail_results', ['run_id'], unique=False)
    op.create_check_constraint(op.f('valid_verdict'), 'classifications', "verdict::text = ANY (ARRAY['PASS'::character varying, 'FAIL'::character varying]::text[])")
    op.create_check_constraint(op.f('valid_severity'), 'classifications', "severity IS NULL OR (severity::text = ANY (ARRAY['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying, 'CRITICAL'::character varying]::text[]))")
    op.drop_constraint(None, 'classifications', type_='foreignkey')
    op.create_foreign_key(op.f('classifications_run_id_fkey'), 'classifications', 'runs', ['run_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_classifications_run_id'), 'classifications', ['run_id'], unique=False)
    # ### end Alembic commands ###
